spring:
  application:
    name: test-app
security:
    oauth2:
      client: 
            client-id: <----->
            client-secret: <----->
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            cleintAuthenticationScheme: form
      resource:
            userInfoUri: https://graph.facebook.com/me